# Python stubs generated by omniidl from idl/emergency.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"idl/emergency.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"idl/emergency.idl")


# interface Emergency_IDL
_0__GlobalIDL._d_Emergency_IDL = (omniORB.tcInternal.tv_objref, "IDL:Emergency_IDL:1.0", "Emergency_IDL")
omniORB.typeMapping["IDL:Emergency_IDL:1.0"] = _0__GlobalIDL._d_Emergency_IDL
_0__GlobalIDL.Emergency_IDL = omniORB.newEmptyClass()
class Emergency_IDL :
    _NP_RepositoryId = _0__GlobalIDL._d_Emergency_IDL[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.Emergency_IDL = Emergency_IDL
_0__GlobalIDL._tc_Emergency_IDL = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_Emergency_IDL)
omniORB.registerType(Emergency_IDL._NP_RepositoryId, _0__GlobalIDL._d_Emergency_IDL, _0__GlobalIDL._tc_Emergency_IDL)

# Emergency_IDL operations and attributes
Emergency_IDL._d_emergency = ((), (), None)

# Emergency_IDL object reference
class _objref_Emergency_IDL (CORBA.Object):
    _NP_RepositoryId = Emergency_IDL._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def emergency(self, *args):
        return _omnipy.invoke(self, "emergency", _0__GlobalIDL.Emergency_IDL._d_emergency, args)

    __methods__ = ["emergency"] + CORBA.Object.__methods__

omniORB.registerObjref(Emergency_IDL._NP_RepositoryId, _objref_Emergency_IDL)
_0__GlobalIDL._objref_Emergency_IDL = _objref_Emergency_IDL
del Emergency_IDL, _objref_Emergency_IDL

# Emergency_IDL skeleton
__name__ = "_GlobalIDL__POA"
class Emergency_IDL (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.Emergency_IDL._NP_RepositoryId


    _omni_op_d = {"emergency": _0__GlobalIDL.Emergency_IDL._d_emergency}

Emergency_IDL._omni_skeleton = Emergency_IDL
_0__GlobalIDL__POA.Emergency_IDL = Emergency_IDL
omniORB.registerSkeleton(Emergency_IDL._NP_RepositoryId, Emergency_IDL)
del Emergency_IDL
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "emergency_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
